import * as React from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useAuth } from '@clerk/nextjs'
import LandingPage from './landing'
import Loading from '@/components/general/Loading'
import { useRouter } from 'next/router'

export default function Home() {
	const { isSignedIn } = useAuth()
	const router = useRouter()

	React.useEffect(() => {
		if (isSignedIn) {
			router.push('/app/initial-intake')
		} else {
			router.push('/landing')
		}
	}, [isSignedIn])

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<>
				<Loading />
			</>
		</>
	)
}
